server:
  port: 9999

website:
  domain: http://117.72.146.138


spring:
  application:
    name: spring-ai-mcp-client
  profiles:
    active: dev
  ai:
    #    mcp:
    #      client:
    #        enabled: true
    #        name: spring-ai-mcp-client
    #        type: ASYNC
    #        sse:
    #          connections:
    #            server1:
    #              url: https://mcp.amap.com
    #              sse-endpoint: /sse?key=298cd53c33d25010d46d6568da77bd75
    #            server2:
    #              url: http://172.16.0.7:9060
    #              sse-endpoint: /sse

  data:
    redis:
      host: 127.0.0.1
      port: 9379
      password: ccckz


internet:
  websearch:
    searxng:
      url: http://172.16.0.7:6080/search
      counts: 10